### ISSUE TITLE
Can reset datagrid itemssource by setting binding object to null?

### ISSUE THREAD

**Issue by sebaarslan** [akgulebubekir/Maui.DataGrid#1]
dataGrid.SetBinding(Maui.DataGrid.DataGrid.ItemsSourceProperty, "Teams");
or
dataGrid.ItemsSource = Teams;

![image](https://user-images.githubusercontent.com/7481458/194754964-57a7fb1d-1db6-4844-9c3e-386a441faa1c.png)

viewModel.Teams = null
or
dataGrid.ItemsSource = null

then grid content should be emptied.

**Comment by akgulebubekir** [comment]
Inorder to manipulate the datasource on your VM, you should use `ObservableCollection<Team>` as `DataSource`

**Comment by sebaarslan** [comment]
I can't use ObservableCollection because I am dynamically creating multiple DataGrid elements.
I set the result to Itemssource directly, like this: dataGrid.ItemsSource = myresults. (a list from my object.)
If there is no result (null), the previous data remains in the datagrid.
If the result is null I will try by creating an empty list. 
dataGrid.ItemsSource = myresults ?? new List<MyObject>();
Thank you.
