### ISSUE TITLE
Error occurs when setting columns in code-behind for net7.0.

### ISSUE THREAD

**Issue by sebaarslan** [akgulebubekir/Maui.DataGrid#10]
.csproj

`<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>`

MainPage.xaml
`<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:dg="clr-namespace:Maui.DataGrid;assembly=Maui.DataGrid"
             xmlns:conv="clr-namespace:Maui.DataGrid.Sample;assembly=Maui.DataGrid.Sample"
             x:Class="Maui.DataGrid.Sample.MainPage">
</ContentPage>`

MainPagex.xaml.cs

`       public partial class MainPage: ContentPage
        {
        public MainPage()
        {
            BindingContext = new MainViewModel();
            InitializeComponent();

            InitDataGrid();
        }

        private void InitDataGrid()
        {
            var dataGrid = new DataGrid
            {
                SelectionEnabled = true,
                RowHeight = 30,
                HeaderHeight = 35,
                FontSize = 14,
                BorderColor = Color.FromArgb("#CCCCCC"),
                HeaderBackground = Color.FromArgb("#E0E6F8"),
                ActiveRowColor = Color.FromArgb("#8899AA"),
                RowsBackgroundColorPalette = new Maui.DataGrid.PaletteCollection()
                {
                    Color.FromArgb("#F2F2F2"),
                   Color.FromArgb("#FFFFFF")
                },
                HorizontalOptions = LayoutOptions.Fill,
                VerticalOptions = LayoutOptions.Fill,
            };

            var imageTemplate = new DataTemplate(() =>
            {
                Microsoft.Maui.Controls.Image cellImage = new Microsoft.Maui.Controls.Image
                {
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center,
                    Aspect = Aspect.AspectFill,
                    Margin = new Thickness(2)
                };

                cellImage.SetBinding(Microsoft.Maui.Controls.Image.SourceProperty, new Binding("."));

                return cellImage;
            });

            var formattedString = new FormattedString();
            formattedString.Spans.Add(new Span { Text = "Home", TextColor = Colors.Black, FontSize = 13, FontAttributes = FontAttributes.Bold });
            formattedString.Spans.Add(new Span { Text = " (win-loose)", TextColor = Color.FromArgb("#333333"), FontSize = 11, FontAttributes = FontAttributes.Bold });

            var bgColorTemplate = new DataTemplate(() =>
            {
                ContentView contentView = new ContentView
                {
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill
                };

                contentView.SetBinding(ContentView.BackgroundColorProperty, new Binding(".", BindingMode.OneWay, converter: new StreakToColorConverter()));
                var label = new Label
                {
                    HorizontalOptions = LayoutOptions.Center,
                    VerticalOptions = LayoutOptions.Center,
                    TextColor = Colors.Black
                };
                label.SetBinding(Label.TextProperty, new Binding("."));
                contentView.Content = label;
                return contentView;
            });

            var dataGridColumnCollection = new ColumnCollection
            {
                new Maui.DataGrid.DataGridColumn
                {
                    Title = "Logo",
                    PropertyName = "Logo",
                    SortingEnabled = false,
                    CellTemplate = imageTemplate
                },
                new Maui.DataGrid.DataGridColumn
                {
                    Title = "Team",
                    PropertyName = "Name"
                },

                new Maui.DataGrid.DataGridColumn
                {
                    Title = "Win",
                    PropertyName = "Win"
                },
                new Maui.DataGrid.DataGridColumn
                {
                    Title = "Loose",
                    PropertyName = "Loose"
                },
                new Maui.DataGrid.DataGridColumn
                {
                    FormattedTitle = formattedString,
                    PropertyName = "Home"
                },
                new Maui.DataGrid.DataGridColumn
                {
                    Title = "Percentage",
                    PropertyName = "Percentage",
                    StringFormat = "{}{0:0.00}"
                },
                new Maui.DataGrid.DataGridColumn
                {
                    Title = "Streak",
                    PropertyName = "Streak",
                    CellTemplate = bgColorTemplate
                }
            };

            dataGrid.Columns = dataGridColumnCollection;
            dataGrid.SetBinding(DataGrid.ItemsSourceProperty, new Binding("Teams"));
            this.Content = dataGrid;
        }
    }`

![image](https://user-images.githubusercontent.com/7481458/205586036-6b71eb57-4f46-46a4-926b-eaecbc41aec1.png)

**Comment by sebaarslan** [comment]
tested in ui thread, same error.

**Comment by sebaarslan** [comment]
Error message: Method not found: void Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped(System.EventHandler)

Thanks in advance

**Comment by manojit** [comment]
I am also getting the same error. Please help

**Comment by mace04** [comment]
Getting exactly the same as well with a very simplistic XAML entry for the datagrid
![image](https://user-images.githubusercontent.com/39385712/209366517-374e3a23-5548-4345-8fb4-534d017052e2.png)
