### ISSUE TITLE
CommandParameter for PullToRefreshCommand

### ISSUE THREAD

**Issue by Glutarios** [akgulebubekir/Maui.DataGrid#101]
How can I pass the CommandParameters for the PullToRefreshCommand as it is possible in the RefeshView?

Example
`<RefreshView Command="{Binding RefreshCommand}" CommandParameter="{Binding Id}" IsRefreshing="{Binding IsBusy}">`

**Comment by akgulebubekir** [comment]
Unfortunatelly It is not possible at the moment.

**Comment by Glutarios** [comment]
It would be great if they could implement this

**Comment by symbiogenesis** [comment]
This was added to main.
