### ISSUE TITLE
Set sorting order programmatically?

### ISSUE THREAD

**Issue by YBTopaz8** [akgulebubekir/Maui.DataGrid#102]
Hi, 
I've been using your control lately and I'd like to thank you for this!
I have a list that I want to be displayed in Descending Order of a column (when the DataGrid loads for example)
I just wondered if it is possible to set the sorting programmatically, as I explored, we can set it to None, Ascendant and Descendant, like here:
![image](https://github.com/akgulebubekir/Maui.DataGrid/assets/41630728/a9e4b9c5-92e1-4167-9ef7-72214e93899a)

Sorting is done by clicking on the header, but I can't seem to find the code to do in code behind.
So far, _my workaround_ is, I sort the list before assigning it (Maybe it can help anyone)
![image](https://github.com/akgulebubekir/Maui.DataGrid/assets/41630728/be8525e3-a22f-4237-b649-7b60945e6bab)

**Comment by akgulebubekir** [comment]
you can use `SortedColumnIndex` in `DataGrid`

**Comment by YBTopaz8** [comment]
I did !
When I do SortedColumnIndex = 0 (for my first column), it will only sort in ascending order, but my aim would be to sort in DescendingOrder instead.
Since the Grid is aimed at showing recent data first.
Hence why I talked about sorting in general.

**Comment by akgulebubekir** [comment]
then you can use a SortData object instead.

datagrid.SortedColumnIndex = SortData(0, SortingOrder.Descendant)

**Comment by YBTopaz8** [comment]
Thank you!!
