### ISSUE TITLE
Databinding issue

### ISSUE THREAD

**Issue by hhgm** [akgulebubekir/Maui.DataGrid#105]
**Describe the bug**
I am filling my datagrid with an observablecollection containing objects with 3 fields, all strings
I am creating DataTemplates and setting combo boxes (from syncfusion) and the itemssource is working fine, and selected item seems to be working as well, but when I pick a different value, I can see that syncfusion detects the change, but I can not detect the databinding being updated.. so no update is propagated to the underlying property.

**To Reproduce**
My class: 
using CommunityToolkit.Mvvm.ComponentModel;

namespace SharedModels.Models
{
    public class SatelliteModeConfiguration : ObservableObject
    {
        private string _viewPath = String.Empty;
        private string? _decorations;
        private bool _isDirty;

        public SatelliteModeConfiguration() { }
        public SatelliteModeConfiguration(string mode, string viewPath, string decorations)
        {
            Mode = mode;
            _viewPath = viewPath.Trim();
            _decorations = decorations;
        }

        public string Mode { get; set; } = string.Empty;

        public string ViewPath
        {
            get => _viewPath;
            set
            {
                if (_viewPath == value)
                    return;
                _viewPath = value;
                IsDirty = true;
                
                if (!ChangedProperties.Contains(nameof(ViewPath)))
                    ChangedProperties.Add(nameof(ViewPath));
                OnPropertyChanged();
            }
        }

        public string Decorations
        {
            get => _decorations;
            set
            {
                if (_decorations == value)
                    return;
                IsDirty = true;
                if (!ChangedProperties.Contains(nameof(Decorations)))
                    ChangedProperties.Add(nameof(Decorations));
                _decorations = value;
                OnPropertyChanged();
            }
        }

        public bool IsDirty
        {
            get { return _isDirty; }
            set
            {
                if (_isDirty == value)
                    return;
                _isDirty = value;
                OnPropertyChanged();
            }
        }

        public List<string> ChangedProperties { get; set; } = new();
    }
}

SelectedSatellite.Config.Modes = public ObservableCollection<SatelliteModeConfiguration> Modes

My grid:
                    <dg:DataGrid Grid.Row="5" Grid.Column="0" Grid.ColumnSpan="2" ItemsSource="{Binding SelectedSatellite.Config.Modes}" IsEnabled="{Binding SelectedSatellite.IsConnected, Mode=OneWay}">
                        <dg:DataGrid.Columns>
                            <dg:DataGridColumn Title="Mode" PropertyName="Mode" />
                            <dg:DataGridColumn Title="View" PropertyName="ViewPath">
                                <dg:DataGridColumn.CellTemplate>
                                    <DataTemplate>
                                        <StackLayout Orientation="Vertical" VerticalOptions="Center">
                                            <control:SfComboBox
                                                ItemsSource="{Binding Source={RelativeSource AncestorType={x:Type viewModels:DevicesViewModel}}, Path=SelectedSatellite.Templates, Mode=OneWay, Converter={StaticResource PrefixListItemsConverter}, ConverterParameter=Templates/}" 
                                                SelectedItem="{Binding Mode=TwoWay}"
                                                IsEnabled="{Binding Source={RelativeSource AncestorType={x:Type viewModels:DevicesViewModel}}, Path=SelectedSatellite.IsConnected, Mode=OneWay}"/>
                                        </StackLayout>
                                    </DataTemplate>
                                </dg:DataGridColumn.CellTemplate>
                            </dg:DataGridColumn>
                            <dg:DataGridColumn Title="Decorations" PropertyName="Decorations">
                                <dg:DataGridColumn.CellTemplate>
                                    <DataTemplate>
                                        <StackLayout Orientation="Vertical" VerticalOptions="Center">
                                            <control:SfComboBox
                                                ItemsSource="{Binding Source={RelativeSource AncestorType={x:Type viewModels:DevicesViewModel}}, Path=SelectedSatellite.Decorations, Mode=OneWay}" 
                                                SelectedItem="{Binding Mode=TwoWay}" 
                                                IsEnabled="{Binding Source={RelativeSource AncestorType={x:Type viewModels:DevicesViewModel}}, Path=SelectedSatellite.IsConnected, Mode=OneWay}"/>
                                        </StackLayout>
                                    </DataTemplate>
                                </dg:DataGridColumn.CellTemplate>
                            </dg:DataGridColumn>
                        </dg:DataGrid.Columns>
                        <dg:DataGrid.RowsBackgroundColorPalette>
                            <dg:PaletteCollection>
                                <Color>#F2F2F2</Color>
                                <Color>#FFFFFF</Color>
                            </dg:PaletteCollection>
                        </dg:DataGrid.RowsBackgroundColorPalette>
                    </dg:DataGrid>

**Expected behavior**
I would expect the underlying property to be updated according to the selection (and the combobox I use any other places in my app with no problems)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows + Android

**Smartphone (please complete the following information):**
- MAUI

**Additional context**

**Comment by symbiogenesis** [comment]
There seems to be a MAUI bug that is sometimes forcing us to make extra CollectionChanged events in order to cause an update.

I posted in another thread the following code to force updates:

Forcing the CollectionChanged event to fire is something that I have accomplished in my app by calling the following workaround method (ForceNotifyCollectionChanged) after every data change. After MAUI fixes the bug, this stupid code could be removed..

```csharp
    public ObservableCollection<RecordPhoto> RecordPhotos { get; set; }

    private async Task OnDeletePhoto(RecordPhoto? photo)
    {
        this.RecordPhotos.Remove(photo);

        var removed = this.dbContext.RecordPhotos.RemoveIfExists(photo);

        if (removed)
        {
            _ = await this.dbContext.SaveChangesAsync();
        }

        this.ForceNotifyCollectionChanged();
    }

    private void ForceNotifyCollectionChanged()
    {
        // TODO: Remove this whenever MAUI updates the collection correctly. https://github.com/dotnet/maui/issues/8534
        var tempRecordPhoto = new RecordPhoto(null);
        this.RecordPhotos.Add(tempRecordPhoto);
        _ = this.RecordPhotos.Remove(tempRecordPhoto);
    }
```
