### ISSUE TITLE
Wrong headerdisplay in .Net 8 Preview 5

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Maui.DataGrid#107]
I have updated my Maui project to .Net 8 Preview 5. But now the column and row display of my datagrid is wrong. (Platform is iOS.)

![grafik](https://github.com/akgulebubekir/Maui.DataGrid/assets/34155651/56e1ef57-0e30-45ba-8690-68bf320143dc)

**Comment by symbiogenesis** [comment]
I think this is a result of a platform bug when resizing the window. Various bugfixes have made it in even within the past few weeks. But feel free to send them the bug report, and include a test case with steps to reproduce it.
