### ISSUE TITLE
Live data situation with sort

### ISSUE THREAD

**Issue by gvescu** [akgulebubekir/Maui.DataGrid#110]
Hello! First of all, your component rocks!

Now, I have a situation with a datagrid in which the data is updated very frequently. I haven't found a way to reorder the collection, so I was trying to keep the grid updated using `SortedColumnIndex = 0` since that column would tell me the item position (it's a timing table). The problem is that whenever I click to order by that value it works, but it's not sorted in real time.

Am I missing something or is something not available on the plugin yet?

Thanks!

**Comment by symbiogenesis** [comment]
I think what you are saying is that you want a bunch of things sorted in descending order, but adding live data doesn't keep it sorted. So the new data will just be at the end, regardless of whether the DataGrid is sorted.

If i'm understanding correctly, then this is a true bug.

The InternalItems property has a CollectionChanged event attached to it. That calls Reload().

I will update this logic to handle this case, without  incurring a performance cost in all the other places we call Reload().

**Comment by symbiogenesis** [comment]
Let me know if this branch works for you

https://github.com/akgulebubekir/Maui.DataGrid/pull/114
