### ISSUE TITLE
COMException in WinRT.Runtime.dll : Need help for column reordering enhancement

### ISSUE THREAD

**Issue by leonianto** [akgulebubekir/Maui.DataGrid#111]
Hi all,

**Describe the bug**
I am not sure this is a bug because i made some changes to this repo to implement new functionalities so probably it's my fault. But in any case i need your help. Your dataGrid is awesome but for my project i want to add the possibility of reordering columns. So i added an imageButton to the left of the header  to do this (in a new column). If clicked, it shows a collectionView with ItemsSource Columns. If I swap the first column with the second one (with drag and drop) i get a weird exception. From your code, in InitHeaderView, I know that i should reassign the col.headerView using GetHeaderViewForColumn(col, i). But of course you didn't managed this case and you assign that variable only one time and if it is null. Changing ??= to = doesn't work well. So, i tried a different approach. At the button click i remove the onColumnChanged event and I've added a save button to make only "controlled" modifications to the observable collection. Then, i rewrite col.headerView calling GetHeaderViewForColumn and next the reload function. At last i restored the event back to OnColumnChanged. But the exception still remains. I think there is something related to the rendering or to the observable collection modification. Can you help me to find the problem? 

Forked Repo:
[https://github.com/leonianto/Test.Maui.DataGrid.git](url)

The exception is System.Runtime.InteropServices.COMException in WinRT.Runtime.dll: no installed components were detected but I don't know what it refers to. 

I need to update col.headerView because i think that the command behind remains with the old SortedColumnIndex and then after i have swapped name with Id, if i click on "name" header, sorting will have effect on Id column (this happens if you keep ??= in the code). So ... in this case after changes header is correctly updated but its command no. At the beggining i was using a separated window, now simply ignore it.

**To Reproduce**

1. Run the application with TestDataGrid as startup project (Windows Platform)
2. Go to DataGridUserPreferences clicking on the gear icon at the left of the header
3. Swap "name" item with "id" item and click save (but it's the same with whatever swap you do)
4. Click on save
5. See error

**Expected behavior**
After save button click, user preferences panel will be hidden and the datagrid will be reloaded with the new column order. Clicking in a column header the related values will be sorted correctly.  

**Screenshots**
![image](https://github.com/akgulebubekir/Maui.DataGrid/assets/49614467/3938de59-3fd5-42e6-86c5-2ba1f8d96b68)
![image](https://github.com/akgulebubekir/Maui.DataGrid/assets/49614467/1bd3e475-318d-4527-bd50-ca9a59966b7d)

**Additional context**
Maybe, to see this exception in Visual studio 2022, you need to go to Debug -> Windows -> Exception Settings and check  System.Runtime.InteropServices.COMException in  "Common Language Runtime Exceptions" 

If you could help me I would really appreciate it. 
Thank you, 
Antonio

**Comment by symbiogenesis** [comment]
Reordering columns is an excellent new feature.

In my opinion, the easiest way to implement this would be to add a button that would trigger the Popup control from CommunityToolkit.Maui

Inside the Popup, there would be a CollectionView that leverages the [drag-and-drop reordering](https://github.com/dotnet/maui/pull/3768) feature.

Then the result of the Popup would be a collection of DataGridColumn objects (which are our version of column definitions).

This would then update the ColumnsProperty, and the ColumnsProperty already handles PropertyChanged events in the latest master.

The Sample app shows this being used to dynamically add columns.

**Comment by symbiogenesis** [comment]
By the way, you can do all of this without modifying the actual library code for this project, because you can just bind to the Columns property and implement the reordering yourself, just as I described, in your application code.

**Comment by symbiogenesis** [comment]
Another option would be to inherit from the DataGrid and then manipulate the ObservableCollection that is backing the Columns property in the code-behind, which is more like how the sample app does it.

But simply binding to the Columns property is a more MVVM-style approach.

```xaml
<dg:DataGrid Columnts="{Binding MyColumns}" />
```

**Comment by symbiogenesis** [comment]
It may be something with your project.

Try forking the project again and just modify the sample app.

It already allows adding columns.

So use the same structure, but make it reorder the columns instead of add them.

If the sample app doesn't work then maybe it has to do with some configuration issue on your system. Because that works for me.

**Comment by leonianto** [comment]
Yes i  just finished modifying the sample. I worked only in Maui.DataGrid.Sample. I've added a popup in which i inserted the collectionView with ItemsSource Columns. In MainPage i've added the imagebutton to open the popup with this clicked event: 
   
```c#
private async void OpenPopupButtonClick(object sender, EventArgs e)
    {
        var popup = new DataGridUserPreferencesPopup(_dataGrid1.Columns);
        await this.ShowPopupAsync(popup);
    }
``` 

In MainProgram i had also called the UseMauiCommunityToolkit() method.

CollectionView in the popup:
```
  <CollectionView x:Name="CVColumns" CanReorderItems="True">
            <CollectionView.ItemTemplate >
                <DataTemplate>
                    <Border Stroke="#FFFFFFFF" StrokeThickness="2" StrokeShape="RoundRectangle 8,8,8,8" HorizontalOptions="Center">
                        <Label Text="{Binding  Title}" FontSize="16" HeightRequest="30" Margin="5" HorizontalOptions="Center" ></Label>
                    </Border>
                </DataTemplate>
            </CollectionView.ItemTemplate>
            <CollectionView.ItemsLayout >
                <LinearItemsLayout Orientation="Vertical"
                           ItemSpacing="10"  />
            </CollectionView.ItemsLayout>
        </CollectionView>
```       

I can reorder the items in the collectionView and the datagrid follow the changes but if i try to sort a column it gives me the same error.
