### ISSUE TITLE
Row spacing

### ISSUE THREAD

**Issue by NormskiJJO** [akgulebubekir/Maui.DataGrid#12]
Too much row spacing, try removing the image from the sample app and then change RowHeight to 22. There's too much white space around the row.

**Comment by symbiogenesis** [comment]
A bunch of changes have happened in the meantime, and there shouldn't be much padding to the cells at the moment.

Your comment isn't specific enough to warrant action. If you add some screenshots and a particular suggestion, then we can act.

It is possible to set your own DataTemplate for each column, and in there set whatever layout you want.

I am closing this issue now, but you may feel free to respond with more detail after you test the latest code, and I can re-open it if need be.
