### ISSUE TITLE
BorderColor wrong behaviour

### ISSUE THREAD

**Issue by Petrarca181** [akgulebubekir/Maui.DataGrid#120]
**Describe the bug**
BorderColor sets background/fill color not  the stroke to the border. Basically datagrid background becomes black.  

**To Reproduce**
Blank maui app
Empty datagrid

**Expected behavior**
BorderColor property should set stroke color?

**Screenshots**
<details>
  <summary>Property not set/default</summary>
<img src="https://github.com/akgulebubekir/Maui.DataGrid/assets/54235138/ef4bf47e-4cc8-4069-b6b4-7f1e60d3f9a7">
</details>

<details>
  <summary> BorderColor="Red"</summary>

<img src="https://github.com/akgulebubekir/Maui.DataGrid/assets/54235138/76c14b03-b76b-4301-a8de-8e32c9309414">

</details>

**MAUI (please complete the following information):**
 - Android api 33

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab A8
 - Last official firmware

**Comment by symbiogenesis** [comment]
Yes, this is how the borders were constructed originally.

To change this would require a fairly radical reworking of all the styling. Which we probably should do anyways, just to allow everything to look really pretty.

Last time I tried to fix this, I ran into problems. But now I understand this project way better, and will give it a try.
