### ISSUE TITLE
Issue with activity indicator and column width

### ISSUE THREAD

**Issue by manojit** [akgulebubekir/Maui.DataGrid#13]
1. I am trying to OFF the activity indicator on PullToRefresh. Setting IsRefreshing to false but still, it shows that. It was never going OFF.
2.  Adding columns dynamically and setting Width = GridLength.Auto. This is fixing the header column properly but values are not fixed on the same alignment.  I need dynamic column lengths 

Please help

**Comment by symbiogenesis** [comment]
Try now

**Comment by symbiogenesis** [comment]
For the second issue, you could try adding a binding to the DataGridColumn.Width property.

For instance, with a converter that holds a stateful field to remember the widest cell. I didn't test this code, but you could try it.

```csharp
internal class BoolToSelectionModeConverter : IValueConverter
{
    private GridLength _widestCellLength = new(0);

    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is GridLength gridLength)
        {
            if (gridLength.IsAuto)
            {
                throw new InvalidOperationException("This converter is not meant to handle auto widths");
            }

            if (gridLength.IsStar || gridLength.Value > _widestCellLength.Value)
            {
                _widestCellLength = gridLength;
                return gridLength;
            }
        }

        return _widestCellLength;
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
```

**Comment by symbiogenesis** [comment]
Turns out there was also a bug in MAUI

https://github.com/dotnet/maui/issues/12977
