### ISSUE TITLE
Databound celltemplate items not updating underlying property

### ISSUE THREAD

**Issue by hhgm** [akgulebubekir/Maui.DataGrid#131]
**Description**
I have created a datagrid. This grid contains a number of columns, and from here on I will focus on just one, as this is where I see the issue. I have defined a celltemplate and inside it I am using a Picker control. The Picker is databound as everything else, and works fine. 

`
                    <dg:DataGrid x:Name="dataGrid"
                                     Grid.Row="6" 
                                     Grid.Column="0" 
                                     Grid.ColumnSpan="2"
                                     ItemsSource="{Binding SelectedSatellite.Config.Modes}">
                        <dg:DataGrid.Columns>
                            <dg:DataGridColumn Title="Template"
                                                         PropertyName="ViewPath"
                                                         Width="*">
                                <dg:DataGridColumn.CellTemplate>
                                    <DataTemplate>
                                            <Picker 
                                                    ItemsSource="{Binding Source={RelativeSource AncestorType={x:Type viewModels:DevicesViewModel}}, Path=SelectedSatellite.Templates, Mode=OneWay, Converter={StaticResource PrefixListItemsConverter}, ConverterParameter=Templates/}"
                                                    SelectedItem="{Binding Mode=TwoWay}">
                                            </Picker>
                                    </DataTemplate>
                                </dg:DataGridColumn.CellTemplate>
                            </dg:DataGridColumn>
                        </dg:DataGrid.Columns>
                        <dg:DataGrid.RowsBackgroundColorPalette>
                            <dg:PaletteCollection>
                                <Color>#F2F2F2</Color>
                                <Color>#FFFFFF</Color>
                            </dg:PaletteCollection>
                        </dg:DataGrid.RowsBackgroundColorPalette>
                    </dg:DataGrid>`

When I change the selected item in the Picker, I can see that the UI part works fine, and if I attach an event handler to the selecteditemchanged event, I can see that the SelectedItem is changed. What is NOT working is the relaying of that change to the underlying property of the databound item. Setting a breakpoint on the setter here, nothing happens.

**Expected behavior**
I would expect the underlying property to be updated when the SelectedItem was changed as per the databinding.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser N/A

**Additional context**
Included in a MAUI project bases on .NET 7 executing under Windows Machine setup.

**Comment by symbiogenesis** [comment]
The approach you used of setting the selected item to be the grandparent of the actual ItemsSource is a bad design choice. You should store the SelectedItem in an unrelated object.
