### ISSUE TITLE
Add ability to set SortingOrder property

### ISSUE THREAD

**Issue by adammast** [akgulebubekir/Maui.DataGrid#154]
When creating a data grid in xaml you can set the SortedColumnIndex but have no way to specify the SortingOrder so it defaults to ascending order. There should be a new bindable property (if that's the correct thing) added to customize SortingOrder on creation.

**Comment by symbiogenesis** [comment]
You can set the sorting order by setting the sort index to negative, for descending. Or you could pass a SortData object that contains the same information.
