### ISSUE TITLE
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

### ISSUE THREAD

**Issue by 7runks** [akgulebubekir/Maui.DataGrid#158]
Project fails to start on Android Emulator or a real mobile.

1. Go to 'Visual Studio 2022'
2. Click on 'Tools'
3. Click on 'Nuget Package Manager'
4. Click on 'Manage Nuget Packages for Solution'
5. Click on 'update'
6. Click on 'akgul.Maui.DataGrid to version 4.01'

**Expected behavior**
Projects compiles without any problem.

 - OS: Windows 11.

**Additional context**
Going back to version 4.0, fixes it.

**Comment by 7runks** [comment]
Actually, Going back to version 3.0, fixes it.

**Comment by symbiogenesis** [comment]
If you could provide a sample repository, that would be helpful. But if you want the new features, the current main branch is hopefully working.

**Comment by symbiogenesis** [comment]
Closing unless I hear more. The main branch is quite a bit different from 4.0.1 by now.
