### ISSUE TITLE
Set the page number to 1 when the collection has changed.

### ISSUE THREAD

**Issue by olivierxpmetal** [akgulebubekir/Maui.DataGrid#159]
**Describe the bug**
When the collection size requires pagination, if the user moves to one of the following pages, downsizing the collection displays an empty list. The user can no longer select a lower page.

**To Reproduce**
I use the binding for the ItemsSource and the PullToRefreshCommand calls a command that refreshes the ItemsSource.
1. Create a datagrid whit PaginationEnabled=true and PageSize=5.
2. Assign a collection to the ItemsSource. The collection must contain 6 or more items.
3. Use a button to reduce the collection size to less than 5.
4. Start the application and go to page 2 of the datagrid.
5. Click on the reduce collection size button.
6. The datagrid does not display the list and it is impossible to return to page 1.

**Expected behavior**
When changing ItemsSource, automatically select page 1.

**Desktop (please complete the following information):**
 - OS: Win 10
 - .NET MAUI 8.0
 - DataGrid Version  4.0.1

**Smartphone (please complete the following information):**
Not tested

**Comment by symbiogenesis** [comment]
Interesting bug. I will look at this.

**Comment by symbiogenesis** [comment]
Does this PR fix it for you:

https://github.com/akgulebubekir/Maui.DataGrid/pull/160
