### ISSUE TITLE
Selected Item corrupts after scroll or rebind.

### ISSUE THREAD

**Issue by HarborIntex** [akgulebubekir/Maui.DataGrid#162]
I am binding the grid to a dataset and then preselecting the first row.
The grid contains 20 or so rows with the first 5 visible.  
Selecting of the visible rows works fine, firing the ItemSelected event.

However - if you scroll so the first rows are not visible and then scroll back - then those rows do not select with the Selected Row color however the event still fires correctly. 

If I then rebind - it selects the first row again properly - but then if you tap to select any other row - the ItemSelected fires but the visible selected row remains the first row.

Thoughts on what is going on?  In summary - the grid works fine - but the visible selected row becomes corrupt.

**Comment by symbiogenesis** [comment]
What platform is this? What .NET version? Also, can you repeat this using the sample app with the current main branch?

My guess is this sounds like a platform-specific issue. But I know that the selected item is lost during pagination. I opened an issue about that already:

https://github.com/akgulebubekir/Maui.DataGrid/issues/157

**Comment by HarborIntex** [comment]
.NET 8 and Android. 
I don't think it is scrolling issue because even on a rebind it does the same thing.  

- For instance - it will load the 15 records with the first 5 visible.  
- Click on the 2nd and 3rd rows and it becomes the active row as expected.
- Rebind the dataset and while the ItemSelected event will still fire - the active row will no longer update.

**Comment by HarborIntex** [comment]
This is also now working after 4.04 (or possibly 2 or 3  - I did not specifically retest after either of those).
