### ISSUE TITLE
RowsBackgroundColorPalette does not always get reapplied after sorting.

### ISSUE THREAD

**Issue by chrigi28** [akgulebubekir/Maui.DataGrid#164]
**Describe the bug**
When sorting by a column the RowsBackgroundColorPalette does not always get reapplied, sometimes it does sometimes not. Couldn't find a proper cause. But its 100% reproduceable when sorting the provided example by Streak

**To Reproduce**
1. Go run the sample Project 
2. Disable Pagination (for clearer result)
3. Sort by Streak
4. See error background colors of row

**Expected behavior**
The RowsBackgroundColorPalette should be reapplied after sorting to be bright / dark / bright / dark ....

**Screenshots**
![image](https://github.com/akgulebubekir/Maui.DataGrid/assets/28056681/9b163c06-03f7-4047-b635-e0b66842b7a6)

**Desktop (please complete the following information):**
 - OS: Windows 19045.4046

**Smartphone (please complete the following information):**
- Not checked

**Additional context**
Sorting by other columns for example Won does sometimes the same by clicking and sorting multiple by Won it does sometimes fix it.

**Comment by symbiogenesis** [comment]
With the latest main branch on net8.0-windows10.0.22621.0 with MAUI 8.0.7, I'm not able to replicate it.

**Comment by symbiogenesis** [comment]
I was able to reproduce this only when disabling pagination, and only on the Streak column. Very interesting. Will look at it.

**Comment by symbiogenesis** [comment]
Try the latest main branch now

**Comment by symbiogenesis** [comment]
When using any fancy IComparable logic or duplicate list items, remember that internally C# does index lookups by reference.
