### ISSUE TITLE
How can I remove the black color from below

### ISSUE THREAD

**Issue by spacesdima123456** [akgulebubekir/Maui.DataGrid#165]
![f047de73-f877-426c-970b-1f66a4bee40d](https://github.com/akgulebubekir/Maui.DataGrid/assets/48646924/56d7ca92-935a-41ff-9c12-690cf96e4f7f)  How can I remove the black color from the bottom? The BorderColor property changes color. 
If the BorderColor property is set to Transparent, then everything is ok, but then the head border disappears.

**Comment by symbiogenesis** [comment]
You can try using the current master branch as it has the sensible-colors branch merged now, as of PR https://github.com/akgulebubekir/Maui.DataGrid/pull/121

**Comment by symbiogenesis** [comment]
Until the next version is released, you could clone the main branch and reference it as a project reference instead of a package reference.
