### ISSUE TITLE
Sorting not working with .NET MAUI 8.0.7 or later

### ISSUE THREAD

**Issue by symbiogenesis** [akgulebubekir/Maui.DataGrid#166]
Sorting is broken starting on 8.0.7

Reverting to 8.0.6 fixes it. I set this library to use 8.0.6 for .NET 8 until it is fixed.

It might be related to https://github.com/dotnet/maui/pull/20875 but 8.0.10 and 8.0.14 doesn't seem to have fixed it.

Tracking this here for reference purposes.

**Comment by schlaman** [comment]
I use this control and indeed it is broken now with 8.0.14 (I see from 8.0.7 on)

How do I set this library to use 8.0.6 for .NET 8?
Can I set that in the csproj file for 
<PackageReference Include="akgul.Maui.DataGrid" Version="4.0.2" />

Is there a way to have akgul.Maui.DataGrid only use 8.0.6 of Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility?

Thanks!

**Comment by SpartanNico94** [comment]
Hi, i think i have the same issue because my grid has a very strange behaviour while changing ItemsSource property. 
How can I change the Maui version?

**Comment by SpartanNico94** [comment]
I can confirm that reverting Maui version solves the problem. 
I had a really strange behaviour while updating ItemsSource during runtime and I tried everything before looking at the issues, thanks @symbiogenesis!!

@schlaman you have to revert packages from Nuget

**Comment by symbiogenesis** [comment]
@akgulebubekir now that this is fixed, a new hotfix release is probably warranted.
