### ISSUE TITLE
Can't get commands to work without MVVM

### ISSUE THREAD

**Issue by mtanml** [akgulebubekir/Maui.DataGrid#176]
Excellent grid control, thank you!   I'm just having an issue getting RowTappedCommand to fire.   I'm not using MVVM, so my view is bound to the code behind with Binding = this.

Here's my grid definition:

<dg:DataGrid x:Name="grdResults" ItemsSource="{Binding Results}" SelectedItem="{Binding SelectedLoanType, Mode=TwoWay}" SelectionMode="Single" RowTappedCommand="{Binding ItemTappedCommand}" x:DataType="local:QualifyResultsView">

And the code behind:

public ICommand ItemTappedCommand { get; set; }
BindingContext = this;
ItemTappedCommand = new Command(ItemTapped);
private void ItemTapped(object item){ }

Are you able to assist?   Thanks!

**Comment by symbiogenesis** [comment]
RowTappedCommand is one of the only parts of this library that I've not thought about, as it is a newer feature added by someone else.

I think your code looks fine to me, and it shouldn't matter whether you are using MVVM. Although, this control was clearly made with MVVM support in mind.

If you fork this repo and then modify the sample project to demonstrate the issue, that might help.

Also, make sure you are using the absolute latest version of this library, and the latest MAUI version.

**Comment by mtanml** [comment]
Thanks, Edward! What about ItemSelected? I couldn’t get that to work either.   Any known issues there?





Sent from my iPhone; please excuse any typos




​
Marc Tanberg
Senior Software Developer, Mother Lode Holding Company
t: 877.958.8485    
e: ***@***.***
a: 9087 Foothills Blvd., Ste 700 | 
Roseville, CA  
95747

​
________________________________

**Comment by symbiogenesis** [comment]
Another user has been reporting it, but the rest of us cannot replicate it:

https://github.com/akgulebubekir/Maui.DataGrid/issues/170

**Comment by symbiogenesis** [comment]
maybe do:

`dotnet workload update`

Almost seems like a "works on my machine" type of issue. Which is why I say.

But another user experienced a problem with the ItemSelected event, and switching to the RowTappedCommand is what fixed it for them. https://github.com/akgulebubekir/Maui.DataGrid/issues/173

You could try the reverse of that, and switch to the event.

**Comment by mtanml** [comment]
Hi Edward,

Based on the comments in those other issues that you referred to, I rolled back to version 4.0.1 and the ItemSelected handler works perfectly in that version.

Thank you!

**Comment by symbiogenesis** [comment]
When PR #178 lands, this will probably allow you to update without a problem.
