### ISSUE TITLE
How to use color binding in PaletteCollection?

### ISSUE THREAD

**Issue by heulendoch** [akgulebubekir/Maui.DataGrid#18]
Hello,

is it possible to use 
e. g. {AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}} instead of a hard coded value like #F2F2F2?

    <dg:DataGrid.RowsBackgroundColorPalette>
        <dg:PaletteCollection>
            <Color>#F2F2F2</Color>
            <Color>#FFFFFF</Color>
        </dg:PaletteCollection>
    </dg:DataGrid.RowsBackgroundColorPalette>

**Comment by symbiogenesis** [comment]
You should use a ColorProvider as the author describes here.

https://github.com/akgulebubekir/Maui.DataGrid/pull/5

**Comment by symbiogenesis** [comment]
Mine provides alternating colors for records with a default status, and custom colors for custom statuses, and looks like this

```csharp
public class RecordRowColorProvider : IColorProvider
{
    public Color GetColor(int rowIndex, object item)
    {
        Color defaultColor;

        if (rowIndex % 2 == 0)
        {
            defaultColor = Colors.White;
        }
        else
        {
            defaultColor = Color.FromArgb("#F2F2F2");
        }

        if (item is Record record)
        {
            if (record.IsApproved)
            {
                return (Color)Application.Current!.Resources["ApprovedRecord"];
            }
            else if (record.IsSubmitted)
            {
                return (Color)Application.Current!.Resources["SubmittedRecord"];
            }
            else
            {
                return defaultColor;
            }
        }

        return defaultColor;
    }
}
```
