### ISSUE TITLE
"Position 73:108. StaticResource not found for key PaginationStepperStyle"

### ISSUE THREAD

**Issue by SzergelyHUN** [akgulebubekir/Maui.DataGrid#183]
Hi!
I downloaded the 4.0.0 version and after like 2 days of use I get this error message. I reinstaled the package, removed from the .nuget/package folder but still nothing. I use .NET 7.0 and build for Android
Anybody can help? 
I want to use this in my school project.

**Comment by symbiogenesis** [comment]
try upgrading to 4.0.4

**Comment by SzergelyHUN** [comment]
I cant install it, because I use 7.0 and 4.0.4 need 8.0

**Comment by symbiogenesis** [comment]
You could try 4.0.1 at least:

https://www.nuget.org/packages/akgul.Maui.DataGrid/4.0.1#supportedframeworks-body-tab

**Comment by symbiogenesis** [comment]
Your error is the same as https://github.com/akgulebubekir/Maui.DataGrid/pull/150 which was fixed in 4.0.1
