### ISSUE TITLE
The text Color is not being updated when the grid is on a popup dialog

### ISSUE THREAD

**Issue by DanyAbr1** [akgulebubekir/Maui.DataGrid#184]
**Describe the bug**
I'm written a Maui app only for android. when the datagrid is on a popup dialog the header text color and the row text color doesn't update.

**To Reproduce**

**Expected behavior**
It should use the style that has been set up.

**Screenshots**
"Datagrid on page"
![datagrid-on-page](https://github.com/akgulebubekir/Maui.DataGrid/assets/27693863/e8f04f30-51c0-4490-8078-d08c4665a108)

"Datagrid on popup"
![datagrid-on-popup](https://github.com/akgulebubekir/Maui.DataGrid/assets/27693863/1eb2e060-9f22-49e8-a32b-a423b14f16d7)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: android API 34

**Additional context**

**Comment by symbiogenesis** [comment]
Do you have a minimum reproducible sample? Are you talking about the popup from the CommunityToolkit?

Seems like an upstream bug and you would need to alert the MAUI team.

**Comment by DanyAbr1** [comment]
> Do you have a minimum reproducible sample? Are you talking about the popup from the CommunityToolkit?
> 
> Seems like an upstream bug and you would need to alert the MAUI team.


Yes, I'm talking about maui community toolkit popup

**Comment by symbiogenesis** [comment]
As a workaround until the upstream issues are fixed you can use a custom cell template to manually set colors.
