### ISSUE TITLE
Can't scroll to the last table row

### ISSUE THREAD

**Issue by HelenaLucon** [akgulebubekir/Maui.DataGrid#186]
**Describe the bug**
I can't scroll to the last table row because it is overlaid by the paginator (on android)

**To Reproduce**
1. Open and start Maui.DataGrid.Sample
2. Select 6 Items per Page
3. Scroll to the end
4. Last item is overlaid

**Screenshots**
![Screenshot_1718026294](https://github.com/akgulebubekir/Maui.DataGrid/assets/95741653/f9b5e9e7-0e7e-4e61-9efb-4baaa75e7709)

**Smartphone (please complete the following information):**
 - tested on android 7.1 and android 14

**Comment by MaH1996SdN** [comment]
I have the same issue on Windows.

**Comment by symbiogenesis** [comment]
> I looked at the source code and found the following problem:
> 
> See DataGrid.xaml (Line 49):
> 
> ```
>  <Grid>
>      <Grid.RowDefinitions>
>          <RowDefinition Height="Auto" />
>          <RowDefinition Height="*" />
>          <RowDefinition Height="Auto" />
>      </Grid.RowDefinitions>
>      <local:DataGridHeaderRow Grid.Row="0" x:Name="_headerRow"  .../>
>      <RefreshView Grid.Row="1" x:Name="_refreshView"  Grid.RowSpan="2"  .../>
>       <Grid Grid.Row="2" x:Name="_footerView" .../>
>   </Grid>
> ```
> 
> So there is a grid with three rows for Header, RefreshView (collection of rows) and Footer. In the RefreshView, RowSpan is then set to 2, so that it includes both row no. 0 and no. 1. However, the footer is already in row no. 1. That is why this error occurs. If you delete RowSpan, the error should be resolved.

Thank you for diagnosing the issue.
