### ISSUE TITLE
Filling DataSet from SQL Query

### ISSUE THREAD

**Issue by VegasJohnson** [akgulebubekir/Maui.DataGrid#196]
C#
`SqlDataAdapter sda = new SqlDataAdapter(cmd);
DataSet ds = new DataSet();
sda.Fill(ds);
dataview.ItemsSource = ds.Tables;`

Xmal

` 
<dg:DataGrid x:Name="dataview"  SelectionMode="Single" HeaderBackground="Grey" RowHeight="30" HeaderHeight="25" HeaderBordersVisible="True" Margin="0,5,0,0" >
     <dg:DataGrid.Columns>
         <dg:DataGridColumn Title="Id"  Width="30">
             <dg:DataGridColumn.CellTemplate>
                 <DataTemplate>
                     <Label Text="{Binding Id}"/>
                 </DataTemplate>
             </dg:DataGridColumn.CellTemplate>
         </dg:DataGridColumn>

         <dg:DataGridColumn Title="Business"  Width="60*">
             <dg:DataGridColumn.CellTemplate>
                 <DataTemplate>
                     <Label Text="{Binding c_location}"/>
                 </DataTemplate>
             </dg:DataGridColumn.CellTemplate>
         </dg:DataGridColumn>

         <dg:DataGridColumn Title="Date"  Width="40*">
             <dg:DataGridColumn.CellTemplate>
                 <DataTemplate>
                     <Label Text="{Binding job_date}"/>
                 </DataTemplate>
             </dg:DataGridColumn.CellTemplate>
         </dg:DataGridColumn>

         <dg:DataGridColumn Title="Location"  Width="80*">
             <dg:DataGridColumn.CellTemplate>
                 <DataTemplate>
                     <Label Text="{Binding l_location}"/>
                 </DataTemplate>
             </dg:DataGridColumn.CellTemplate>
         </dg:DataGridColumn>

     </dg:DataGrid.Columns>
     <dg:DataGrid.RowsBackgroundColorPalette>
         <dg:PaletteCollection>
             <Color>#ababab</Color>
             <Color>#FFFFFF</Color>
         </dg:PaletteCollection>
     </dg:DataGrid.RowsBackgroundColorPalette>
 </dg:DataGrid>
`
 
 The Binding is the columns in the database.

**Comment by symbiogenesis** [comment]
Convert the records to a list before binding.

**Comment by symbiogenesis** [comment]
I notice that it looks like you are trying to bind more than one table to the DataGrid, so even if you convert to a list first that isn't enough.

You need to produce a list of objects where all the records are the same.

Thus, you should either bind to a single table, or do the equivalent of joining the tables into one collection of DataTransferObjects.

But it will need to be a more normal IEnumerable at the end. You can't bind directly to a DataTable object.

**Comment by VegasJohnson** [comment]
Yes , this took me gaining 30 more greys but i did achieve this methead.
Thank you for following up.
