### ISSUE TITLE
hi,I have a problem, please take a look

### ISSUE THREAD

**Issue by shadowPhil** [akgulebubekir/Maui.DataGrid#2]
When the number of  data grid columns exceeds the screen width and slide to the screen to view the data, the content is blank

![20221012094752](https://user-images.githubusercontent.com/23468551/195230214-1f934623-d929-4204-86bf-f3891970d334.jpg)

**Comment by akgulebubekir** [comment]
Can you provide 

1. target platform name(ios, android)
2. device name
3. sample code that issue can be reproducable

**Comment by shadowPhil** [comment]
> 
hi，thank you for  your reply.
Platform：Android（Android 12）
Device Name：Mi10（xiaomi 10）
![1](https://user-images.githubusercontent.com/23468551/195268796-58bd9712-4060-4ea0-b517-91eed3f204ca.jpg)

`            WebApiResult<List<DeviceDataInfo>> _result = await iRecordService.GetDeviceDataAsync(dev.id, dataType, selectDate.ToString("yyyy-MM-dd"), selectDate.AddDays(1).ToString("yyyy-MM-dd"));

            if (_result.code != 1)
                return;

            if (_result.data == null)
                return;

            DevDataTable =  _result.data;`

**Comment by akgulebubekir** [comment]
You should use constant with for each column and DataGrid itself when you are using inside a ScrollViewer.
