### ISSUE TITLE
Data Grid not working with proper padding

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [akgulebubekir/Maui.DataGrid#212]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by symbiogenesis** [comment]
Can you explain more? Provide an example?

**Comment by SoumyadipYT-OSS** [comment]
@symbiogenesis Issue solved, there were a bugs in the Property of the DataGrid, now the issue solved!
