### ISSUE TITLE
Update row column data after change de ItemSource

### ISSUE THREAD

**Issue by paoc77** [akgulebubekir/Maui.DataGrid#64]
Hi, in runtime using mvvm community toolkit is possible to update a cell, after some property change?
I set my binding in the view with C#
dataGrid.SetBinding(DataGrid.ItemsSourceProperty, nameof(attachmenListViewModel.Attachments), BindingMode.TwoWay);

in the viewmodel:
public ObservableCollection<AttachmentInfo> Attachments { get; } = new();

I load the data and it shows the info Ok in the Grid

later in a command
 Attachments.First().Status = "Requested";
 Nothing happens
 
 Can you please help me with this issue, I'm missing something ? Thanks

**Comment by symbiogenesis** [comment]
The Attachment object would need to inherit from INotifyChanged and the Status property would need to fire an OnPropertyChanged event in the setter.

If you do that, then the properties should update.

I just tried it, and it works fine.
