### ISSUE TITLE
Pagination Feature Request

### ISSUE THREAD

**Issue by jawand** [akgulebubekir/Maui.DataGrid#69]
**New Feature**

can we have **https://datatables.net/** like search, sort, pagination features?

**Comment by symbiogenesis** [comment]
Sorting was already available. Implemented a PR that offers basic pagination.

Searching is possible to add yourself by filtering the ItemsSource, which can hooked to the DataGrid via data binding, and thus will automatically update as you search.

But yes, having built-in per-column searching could be another worthwhile feature.
