### ISSUE TITLE
Column Header is not created when column is created runtime

### ISSUE THREAD

**Issue by enkaradag** [akgulebubekir/Maui.DataGrid#70]
**Describe the bug**
Column Header is not created when column is created runtime such as:

```
`        DataGridColumn col = new DataGridColumn() {
             Title = "Data Column1",
             PropertyName = "DATACOL1",
             Width = 200,
             HorizontalContentAlignment = LayoutOptions.Start
             };
        grd.Columns.Add(col);
`
```

**To Reproduce**
`DataGrid grd=new DataGrid();
        DataGridColumn col = new DataGridColumn() { Title = "Data Column1", PropertyName = "DATACOL1", Width = 200, HorizontalContentAlignment = LayoutOptions.Start };
`

**Expected behavior**
Header should be created with column outside xaml. 

**Desktop (please complete the following information):**
 - OS: Maui Windows,Android
 - .net 7

**Additional context**
Also changing Column Width doesn't change Header Width

Regards
Ender

**Comment by symbiogenesis** [comment]
Good call. Feature merged.
