### ISSUE TITLE
Grid-Sample on an IPad-Pro: wrong presentation

### ISSUE THREAD

**Issue by FischertBilligheim** [akgulebubekir/Maui.DataGrid#84]
I compiled the grid-sample with my Visual-Studio for Mac - and loaded it to my IPad-Pro.

After loading the App the column-header shows all entries, but the data-part below shows only 3 columns completely and a half of the 4th column.

![2C96FC54-BC14-4276-9016-EAF5DA9E30E4](https://user-images.githubusercontent.com/20623089/227720835-cdac41f4-84d4-42aa-8b38-27d1d3f9e24f.png)

if I try to pan/drag_drop a row then all columns are visible, but half of the rows are missing now. 
![E2B70F9A-9660-4074-8AD8-FF2D7ABA7CDD](https://user-images.githubusercontent.com/20623089/227720856-ac9cb971-56b7-4ec2-b728-bc50743c56f5.png)

Any ideas what‘s going wrong?

**Comment by bmclane** [comment]
@FischertBilligheim this is an issue with the RefreshView on iOS, I believe it should be resolved with this
https://github.com/dotnet/maui/pull/14302
