### ISSUE TITLE
How to preselect a row

### ISSUE THREAD

**Issue by paoc77** [akgulebubekir/Maui.DataGrid#86]
Hi,  is possible to create a grid with a row preselected ?

Thanks

**Comment by akgulebubekir** [comment]
Hi,

Yes its possible. You should set `SelectedItem`property.

**Comment by Javiseeker** [comment]
Hello, Im having an issue trying this out... I'm sure that my grid has the SelectedItem filled at the OnAppearing life cycle but still, the Pre-selected row is not highlighted. Any ideas?

**Comment by jobmen** [comment]
i found SelectedItemproperty can only use once??

**Comment by HarborIntex** [comment]
I am unable to get this to work.  Can someone show the line of code it would take, using the sample, to preselect the Memphis row upon grid load?  I am having a "bang my head on desk" moment.. 

Thanks
