### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by x71hicks** [akgulebubekir/Maui.DataGrid#9]
Hi, thank you control.
the control has a way to move horizontally when there are many columns, I tried with a scrollview and the part that is not on the screen does not render

![imagen](https://user-images.githubusercontent.com/38568359/200202807-1aafacb8-ee57-44b1-935e-a99a737081b3.png)

**Comment by akgulebubekir** [comment]
Will be fixed with the latest version

**Comment by Sofiya-kumar** [comment]
@akgulebubekir I need to scroll horizontally as well when more columns are added. Do you have any update on this
