### ISSUE TITLE
Android version not displaying data

### ISSUE THREAD

**Issue by VailTimBrenner** [akgulebubekir/Maui.DataGrid#93]
The Android version of the grid is not displaying any data, based off of testing the most recent version, unaltered, both on an Android tablet as well as an Android emulator.  
![AndroidDemoNotShowingData](https://github.com/akgulebubekir/Maui.DataGrid/assets/131191064/6e79105d-376c-44b5-bfeb-31cd4feff11b)

It should be noted that the Windows version does display the data correctly in the grid.

**Comment by symbiogenesis** [comment]
What MAUI version and .NET version are you using?

**Comment by VailTimBrenner** [comment]
.Net 7.0 and here’s the information on Maui, etc.:
Installed Workload Id      Manifest Version       Installation Source
--------------------------------------------------------------------------------
maui                       7.0.81/7.0.100         SDK 7.0.200
maui-android               7.0.81/7.0.100         SDK 7.0.200, VS 17.5.33530.505
maui-windows               7.0.81/7.0.100         SDK 7.0.200, VS 17.5.33530.505
maui-maccatalyst           7.0.81/7.0.100         VS 17.5.33530.505
maccatalyst                16.2.2054/7.0.100      VS 17.5.33530.505
maui-ios                   7.0.81/7.0.100         VS 17.5.33530.505
ios                        16.2.2054/7.0.100      VS 17.5.33530.505
android                    33.0.46/7.0.100        VS 17.5.33530.505

Thanks again!

**Comment by VailTimBrenner** [comment]
It does sound like it could be a versioning issue.  I’ll see about updating to a newer version of Maui.  Thanks!

**Comment by VailTimBrenner** [comment]
Awesome, thank you for sending this!

**Comment by symbiogenesis** [comment]
Did that resolve your issue?

**Comment by VailTimBrenner** [comment]
Hey Edward, unfortunately due to our production cycle I’m not able to update to the newest version of Maui at this time.  It may be several weeks before I can actually give this a shot.  My apologies.  Feel free to close the tickets in the meantime, and if we update and continue to run into errors, I’ll let you now.  For the moment, I’m using your release 2.0 version, and I’m able to do what I need to with it.  And I should really thank you and the other developers who’ve worked on this grid, as it’s helped us immensely!  Thanks for all you do!

**Comment by craigpj** [comment]
I was running into the same problem. No rows being rendered. Then I put the datagrid inside a ScrollView and set the HightRequest property on the ScrollView. The rows were then rendered.
I also removed the HeightRequest from the ScrollView and added the HeightRequest property on the DataGrid and the rows were rendered. HeightRequest must be set on datagrid or it's enclosing parent control/element.
MinimumHeightRequest on DataGrid does NOT work.
MaximumHeightRequest on DataGrid DOES work; like HeightRequest.

**Comment by symbiogenesis** [comment]
I recommend forking this project and setting up the Sample app to run inside of a ScrollView, and then filing a bug report with MAUI and linking to your forked repo. Be sure to document the exact versions of MAUI and Android.
