### ISSUE TITLE
Grid no longer vertically scrollable when not using built-in pagination.

### ISSUE THREAD

**Issue by VailTimBrenner** [akgulebubekir/Maui.DataGrid#94]
In the release version 2.0.0 the grid was previously scrollable vertically.  Currently, if the results are longer than the screen, there is no way to scroll vertically to see the additional results.  The use case for this is handling sorting and pagination on the server side instead of client side, where the grid needs to be able to scale dynamically based on the screen size of the device, and where it would extend vertically past the allocated space on the screen.

**Comment by symbiogenesis** [comment]
Thank you for this report. Looking at this now.

**Comment by symbiogenesis** [comment]
What platform did you notice this on? I am able to scroll with pagination enabled or disabled on both Windows and Android.

WinUI scrollbars are hard to see. They auto-hide and are tiny. But a mouse wheel or two-finger gesture on a touchpad work easily.

**Comment by VailTimBrenner** [comment]
It was on the Windows version.  I was unable to see results in the grid in the Android version.

Thanks for looking into these!

**Comment by symbiogenesis** [comment]
Still a problem with the latest main branch and the latest stable MAUI? If you could provide a repository link with reproducible test case, I could try to solve this.
