### ISSUE TITLE
Datagrid without header

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Maui.DataGrid#98]
I have a question:
In my Xamarin app I had a listview positioned inside a scrollview. The list view is bound to a string list that is dynamically filled in the background. This has been causing problems since the MAUI migration.
Is it possible to use the datagrid with only one column without a header (Bindigsource =ObservableCollection<String>) instead of the listview?

**Comment by symbiogenesis** [comment]
You should be able to use a normal CollectionView to suit your needs if you only have one column and don't need a header.

**Comment by symbiogenesis** [comment]
Maui.DataGrid does not offer a way to hide the header. It isn't clear to me what benefit the DataGrid would provide if you have only one column and no headers.

If you had more than one column, then the DataGrid would still provide you the column functionality. So it might be a worthwhile feature.

**Comment by symbiogenesis** [comment]
CollectionView does not require being placed within a ScrollView in order to scroll.

**Comment by symbiogenesis** [comment]
Also, there is a MAUI bug with respect to refreshing the CollectionView with CollectionChanged events via ObservableCollection.

I think it only affects some platforms, but I have had to force updates via different workarounds.

**Comment by SE250880** [comment]
That doesn't help in my case and the Maui bug seems to be the problem here. I want to position the listview in a scrollview with the height of *. The Scrollview around is neccesary for the other controls around the listview. This looks fine until the list content gets to the end of the list. Then the whole control is enlarged to the content of the list. I don't want that, but the size should remain and the list should scroll. This worked fine in Xamarin, but not anymore with MAUI. :-(

**Comment by symbiogenesis** [comment]
Forcing the CollectionChanged event to fire is something that I have accomplished in my app by calling the following workaround method (ForceNotifyCollectionChanged) after every data change. After MAUI fixes the bug, this stupid code could be removed..

```csharp
    public ObservableCollection<RecordPhoto> RecordPhotos { get; set; }

    private async Task OnDeletePhoto(RecordPhoto? photo)
    {
        this.RecordPhotos.Remove(photo);

        var removed = this.dbContext.RecordPhotos.RemoveIfExists(photo);

        if (removed)
        {
            _ = await this.dbContext.SaveChangesAsync();
        }

        this.ForceNotifyCollectionChanged();
    }

    private void ForceNotifyCollectionChanged()
    {
        // TODO: Remove this whenever MAUI updates the collection correctly. https://github.com/dotnet/maui/issues/8534
        var tempRecordPhoto = new RecordPhoto(null);
        this.RecordPhotos.Add(tempRecordPhoto);
        _ = this.RecordPhotos.Remove(tempRecordPhoto);
    }
```

**Comment by SE250880** [comment]
OK, thanks for your help, Hopefully the next MAUI update will bring improvement.
