### ISSUE TITLE
Datagrid background

### ISSUE THREAD

**Issue by SE250880** [akgulebubekir/Maui.DataGrid#99]
I set the backgroundcolor white for the datagrid. This works well for rows with content, but if i have space with no content the color is shown gray? In the xamarin version this space was white too. Is it a bug in the maui version?
![grafik](https://github.com/akgulebubekir/Maui.DataGrid/assets/34155651/f8bd9dab-5882-4c76-9822-afcb41987c85)

**Comment by akgulebubekir** [comment]
which platform are you facing with the problem?

**Comment by symbiogenesis** [comment]
Multiple bugs exist in the current stable version of MAUI

https://github.com/dotnet/maui/issues/9135
https://github.com/dotnet/maui/issues/14966
https://github.com/dotnet/maui/issues/15553
https://github.com/dotnet/maui/issues/15592

**Comment by symbiogenesis** [comment]
The sensible-layout PR may have fixed this. https://github.com/akgulebubekir/Maui.DataGrid/pull/121
